# Generated by Django 5.0.6 on 2024-06-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0002_alter_shipment_packaging'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='unknown order', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('packaging', 'item')},
        ),
    ]
