# Generated by Django 5.0.6 on 2024-06-06 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returnpack', '0003_alter_order_order_number_alter_order_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packaging',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='returnpack.item', unique=True),
        ),
        migrations.AlterField(
            model_name='packagingmouvment',
            name='packaging',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='returnpack.packaging'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='returnpack.item', unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='returnpack.item', unique=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='returnpack.item', unique=True),
        ),
    ]
